
### Creating Ingredients
// name=Cheese&spicy=false&amount=1&veggie=true
// name=Tomato Sauce&spicy=false&amount=1&veggie=true
// name=Pepperoni&spicy=true&amount=1&veggie=false
// name=Mushrooms&spicy=false&amount=1&veggie=true
// name=Tuna&spicy=false&amount=1&veggie=false
POST http://localhost:8080/ingredients
Content-Type: application/x-www-form-urlencoded

name=Tuna&spicy=false&amount=1&veggie=false


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.headers.valueOf("Location")!= null, "Invalid Location");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
  client.global.set("newSlotUrl", response.headers.valueOf("Location"));
  client.global.set("slotId", response.body["slotId"]);
});
%}
###

### Modify Ingredient
PATCH http://localhost:8080/ingredients/0
Content-Type: application/x-www-form-urlencoded

name=Pickles&spicy=false&veggie=true&amount=200

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}
###

### Deleting Ingredient
DELETE http://localhost:8080/ingredients/3

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

### Paged Return
GET http://localhost:8080/ingredients?page=0&size=2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}
###

### Get ALL Ingredients
GET http://localhost:8080/ingredients

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

### Get Ingredient
GET http://localhost:8080/ingredients/4

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}
###

### Get All Spicy Ingredients
GET http://localhost:8080/ingredients?spicy=true

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}
###

###
GET http://localhost:8080/ingredients/26/pizzas

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}
###
